# Generated by Django 4.2.1 on 2024-09-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDistances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_value', models.FloatField(max_length=8, unique=True)),
                ('image_size', models.CharField(max_length=10)),
            ],
        ),
    ]
