# Generated by Django 4.2.1 on 2024-06-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDistances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion', models.DecimalField(decimal_places=3, max_digits=6, unique=True)),
                ('image_size', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['conversion'],
            },
        ),
    ]
