# Generated by Django 4.2.1 on 2024-06-18 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveddistances',
            options={},
        ),
        migrations.RemoveField(
            model_name='saveddistances',
            name='conversion',
        ),
        migrations.AddField(
            model_name='saveddistances',
            name='conversion_value',
            field=models.FloatField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveddistances',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saveddistances',
            name='image_size',
            field=models.CharField(max_length=10),
        ),
    ]
