# Generated by Django 4.2.1 on 2024-06-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveddistances',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='saveddistances',
            name='conversion',
        ),
        migrations.AddField(
            model_name='saveddistances',
            name='conversion_value',
            field=models.FloatField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saveddistances',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saveddistances',
            name='image_size',
            field=models.CharField(max_length=10),
        ),
    ]
