# Generated by Django 4.1.2 on 2023-03-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0002_alter_saveddistances_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='saved_distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, unique=True),
        ),
    ]
