# Generated by Django 4.2.1 on 2024-06-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0002_alter_saveddistances_conversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='conversion',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='saveddistances',
            name='image_size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
