# Generated by Django 4.1.2 on 2023-04-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0003_alter_saveddistances_saved_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='saved_distance',
            field=models.DecimalField(decimal_places=2, max_digits=6, unique=True),
        ),
    ]
