# Generated by Django 4.2.1 on 2024-06-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0003_alter_saveddistances_conversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='conversion',
            field=models.FloatField(null=True),
        ),
    ]
