# Generated by Django 4.2.1 on 2024-06-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0004_alter_saveddistances_conversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveddistances',
            options={'ordering': ['conversion_value']},
        ),
        migrations.RenameField(
            model_name='saveddistances',
            old_name='conversion',
            new_name='conversion_value',
        ),
    ]
