# Generated by Django 4.2.1 on 2024-06-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0005_alter_saveddistances_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='conversion_value',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
