# Generated by Django 4.2.1 on 2024-06-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0006_alter_saveddistances_conversion_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='conversion_value',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, unique=True),
        ),
    ]
