# Generated by Django 4.2.1 on 2024-06-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0007_alter_saveddistances_conversion_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='conversion_value',
            field=models.FloatField(null=True, unique=True),
        ),
    ]
