# Generated by Django 4.2.1 on 2024-06-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0011_alter_saveddistances_conversion_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='conversion_value',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
