# Generated by Django 4.2.1 on 2024-06-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0012_alter_saveddistances_conversion_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='conversion_value',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
