# Generated by Django 4.2.1 on 2024-06-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0013_alter_saveddistances_conversion_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveddistances',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='saveddistances',
            name='conversion_value',
            field=models.FloatField(max_length=8),
        ),
    ]
