# Generated by Django 4.2.1 on 2024-06-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0014_alter_saveddistances_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='conversion_value',
            field=models.FloatField(max_length=8, unique=True),
        ),
    ]
