# Generated by Django 4.2.1 on 2024-06-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseapp', '0017_alter_saveddistances_conversion_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddistances',
            name='conversion_value',
            field=models.FloatField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
