# Generated by Django 4.1.2 on 2023-01-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveddistances',
            options={'ordering': ['saved_distance']},
        ),
    ]
