"""
Django settings for image_analysis project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from csp.constants import SELF, NONE, NONCE


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#load_dotenv()
#key = os.environ.get('S_KEY')
#For ubuntu provide full path
load_dotenv('var/www/mouseframe/django_image_analysis/mouseapp/.env')
key = os.environ.get('S_KEY')


SECRET_KEY=key
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = ['127.0.0.1','mouseframe.pt', 'www.mouseframe.pt']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'mouseapp',
    'import_export',
    'accounts',
    'cache_cleaner',
    'csp',
    # 'defender',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mouseapp.middleware.IPLockMiddleware',
    # 'defender.middleware.FailedLoginMiddleware',
]

# ----------------------------------------------------------------------------#

#CACHE EXAMPLE USING DATABASE CACHE

# Django can store its cached data in your database. This works best if you’ve got a fast, well-indexed database server.

#To use a database table as your cache backend:

#Set BACKEND to django.core.cache.backends.db.DatabaseCache
#Set LOCATION to tablename, the name of the database table. This name can be whatever you want, as long as it’s a valid table name that’s not already being used in your database.
#In this example, the cache table’s name is my_cache_table:

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cache_table",
	"TIMEOUT": None,
    }
}

# CREATE CACHE TABLE ----> python manage.py createcachetable

#------------------------------------------------------------------------------#

#Redis cache configuration

    # 1 - PASS CONFIG in docker redis
    # docker exec -it <container_name> redis-cli
    # config set requirepass <yourpassword>

# redis_pass_dev = os.environ.get('REDIS_PASS')
# DEFENDER_REDIS_URL = f"redis://:{redis_pass_dev}@127.0.0.1:6379/0"

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#         'LOCATION': 'cache_table',
#     },
#     'redis': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': DEFENDER_REDIS_URL,  # Replace with your Redis server info
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }



# Use the Redis cache as the default cache

# CACHES['default'] = CACHES['redis']
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"

# DEFENDER SETTINGS

# DEFENDER_LOGIN_FAILURE_LIMIT = 3
# DEFENDER_COOLOFF_TIME = 30



# #Brute force for IPLockoutMiddleWare
LOGIN_URL = '/authenticate/login'
LOGIN_REDIRECT_URL = 'version'
MAX_FAILED_LOGIN_ATTEMPTS = 3
FAILED_LOGIN_LOCK_DURATION = 14400  # 1 hour is 3600s. Currently set to 30 seconds only for testing purposes, change in prod 

ROOT_URLCONF = 'mouseapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mouseapp.wsgi.application'






# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# if DEBUG:

# Running sqlite3 in django:
# python manage.py dbshell ----> Opens sqlite3 CLI
# SELECT * FROM sqlite_master WHERE type='table';
# DROP TABLE appname_modelname;
# python manage.py migrate --run-syncdb -----> Sync your changes done in sqlite3 CLI with your django app

DATABASES = {
'default': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': str(os.path.join(BASE_DIR, "db.sqlite3"))
    }
} 

# else:
#     DATABASES: {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'mydatabase', #change it databasename
#         'USER': 'mydatabaseuser', #change it database user name
#         'PASSWORD': 'mypassword', # change user database password
#         'HOST': 'localhost',  
#         'PORT': '5432',           
#         },
#     }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Where static files will be collected to (for production)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Extra directories to look for static files (optional)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static', 'static_dirs'),
]

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Storage settings (Django 4.2+)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': MEDIA_ROOT,
        },
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}




#CSP SECTION


CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": [SELF],
        "script-src": [SELF, "https://www.google.com", "https://www.gstatic.com", NONCE],
        "style-src": [SELF, "https://fonts.googleapis.com", "https://www.gstatic.com", NONCE],
        "connect-src": [SELF, "https://www.google.com", "https://www.gstatic.com"],
        "img-src": [SELF, "data:", "blob:"],
        "font-src": [SELF, "https://fonts.gstatic.com"],
        "frame-src": ["https://www.google.com", "https://www.google.com/maps/embed"],
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------- SECURITY CHECKS FOR PROD WITH SSL CERTIFICATE FOR PRODUCTION ONLY ---------------------------#

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
USE_X_FORWARDED_HOST = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# ------------------------------------------------------------- #

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 180 * 60  #3 hours
